# Generated by Django 3.2.5 on 2021-08-05 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperson',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupperson',
            name='data_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
