# Generated by Django 3.2.5 on 2021-08-13 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответ')),
                ('data_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('factor', models.FloatField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='groupperson',
            options={'verbose_name_plural': 'Отделы'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Official',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='person_group',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='namej',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='official',
            field=models.CharField(choices=[('1', 'Уборщик'), ('2', 'Охранник'), ('3', 'Кассир'), ('4', 'Разработчик'), ('5', 'Оператор'), ('6', 'Директор')], default=1, max_length=1, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='groupperson',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='groupperson',
            name='data_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='groupperson',
            name='max_test_factor',
            field=models.FloatField(blank=True, default=1, max_length=10, verbose_name='Максимальный коэффициент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupperson',
            name='pass_test_factor',
            field=models.FloatField(blank=True, default=1, max_length=10, verbose_name='Проходной коэффициент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activate_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Код активации'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='data_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token_data',
            field=models.CharField(blank=True, max_length=255, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='groupperson',
            name='Name_Group',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название отдела'),
        ),
    ]
