# Generated by Django 3.2.5 on 2021-08-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0002_auto_20210813_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='person_group',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='person_manage.groupperson', verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
