# Generated by Django 3.2.5 on 2021-08-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0003_customuser_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='person_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_manage.groupperson', verbose_name='Отдел'),
        ),
    ]
