# Generated by Django 3.2.5 on 2021-08-13 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0004_auto_20210813_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_questions', models.CharField(max_length=255, verbose_name='Вопросы')),
                ('test_answers', models.CharField(max_length=255, verbose_name='Ответы')),
                ('tested_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Тестирование',
            },
        ),
    ]
