# Generated by Django 3.2.5 on 2021-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0005_testresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='test_answers',
            field=models.JSONField(max_length=255, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='test_questions',
            field=models.JSONField(max_length=255, verbose_name='Вопросы'),
        ),
    ]
