# Generated by Django 3.2.5 on 2021-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0005_auto_20210806_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
