# Generated by Django 3.2.5 on 2021-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0006_auto_20210813_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='test_result',
            field=models.CharField(default=1, max_length=255, verbose_name='Итог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresults',
            name='test_sum_factor',
            field=models.IntegerField(default=1, verbose_name='Результат'),
            preserve_default=False,
        ),
    ]
