# Generated by Django 3.2.5 on 2021-08-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0007_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
