# Generated by Django 3.2.5 on 2021-08-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0008_rename_name_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='name',
        ),
    ]
