# Generated by Django 3.2.5 on 2021-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0008_alter_testresults_tested_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='test_time_begin',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала теста'),
        ),
        migrations.AddField(
            model_name='testresults',
            name='test_time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время конца теста'),
        ),
    ]
