# Generated by Django 3.2.5 on 2021-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0010_rename_name_customuser_namej'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
