# Generated by Django 3.2.5 on 2021-08-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0011_customuser_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fio',
        ),
    ]
