# Generated by Django 3.2.5 on 2021-08-09 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0013_customuser_fio'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответ')),
                ('data_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Токен'),
        ),
    ]
