# Generated by Django 3.2.5 on 2021-08-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0015_auto_20210809_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupperson',
            name='max_test_factor',
            field=models.FloatField(blank=True, default=1, max_length=10, verbose_name='Максимальный коэффициент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupperson',
            name='pass_test_factor',
            field=models.FloatField(blank=True, default=1, max_length=10, verbose_name='Проходной коэффициент'),
            preserve_default=False,
        ),
    ]
