# Generated by Django 3.2.5 on 2021-08-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0016_auto_20210810_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionspull',
            name='factor',
            field=models.FloatField(verbose_name='Коэффициент'),
        ),
    ]
