# Generated by Django 3.2.5 on 2021-08-10 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0017_alter_questionspull_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='official',
            field=models.CharField(choices=[('1', 'Уборщик'), ('2', 'Охранник'), ('3', 'Кассир'), ('4', 'Разработчик'), ('5', 'Оператор'), ('6', 'Директор')], max_length=1, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.FloatField(verbose_name='Результат')),
                ('test_mark', models.CharField(max_length=15, verbose_name='Оценка')),
                ('tested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отдел')),
            ],
            options={
                'verbose_name_plural': 'Тестирование',
            },
        ),
    ]
