# Generated by Django 3.2.5 on 2021-08-11 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0018_auto_20210810_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='test_mark',
            field=models.CharField(default='gg', max_length=15, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='tested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='DetailedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('qustion_result', models.CharField(max_length=10)),
                ('test_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_manage.testresults', verbose_name='Номер теста')),
            ],
        ),
    ]
