# Generated by Django 3.2.5 on 2021-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0020_auto_20210811_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedtestresult',
            name='test_number',
            field=models.IntegerField(verbose_name='Номер теста'),
        ),
    ]
