# Generated by Django 3.2.5 on 2021-08-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0021_alter_detailedtestresult_test_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresults',
            name='test_number',
        ),
        migrations.AlterField(
            model_name='detailedtestresult',
            name='test_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_manage.testresults', verbose_name='Номер теста'),
        ),
    ]
