# Generated by Django 3.2.5 on 2021-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_manage', '0023_alter_detailedtestresult_test_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedtestresult',
            name='factor',
            field=models.FloatField(default=1, verbose_name='Коэффициент'),
            preserve_default=False,
        ),
    ]
